AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  access-log-lambda

  Sample SAM Template for access-log-lambda

Globals:
  Function:
    Timeout: 10
    CodeUri: ./access-log

Parameters:
  S3BucketName:
    Type: String
    Default: chunnoo-test-bucket
  PrivateKeyParameterName:
    Type: String
    Default: AccessLogPrivateKey

Resources:
  AccessLogFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref S3BucketName
        - SSMParameterReadPolicy:
            ParameterName: !Ref PrivateKeyParameterName
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./access-log
      Dockerfile: Dockerfile
